apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: "2022-08-03T08:33:57Z"
  generation: 1
  labels:
    app: linglong-server
  name: linglong-server
  namespace: linglong
  resourceVersion: "1103081"
  uid: 4ca148cc-32d4-4801-b226-f27d9c77e12d
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: linglong-server
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: linglong-server
    spec:
      containers:
      - image: hub.deepin.com/wuhan_v23_linglong/linglong-server:develop-snipe
        imagePullPolicy: IfNotPresent
        name: linglong-server
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        ports:
          - containerPort: 8888
        volumeMounts:
          - name: linglong-server-data
            mountPath: /data/linglong
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
        - name: linglong-server-data
          persistentVolumeClaim:
            claimName: linglong-server-pv
status:
  conditions:
  - lastTransitionTime: "2022-08-03T08:33:57Z"
    lastUpdateTime: "2022-08-03T08:33:57Z"
    message: Deployment does not have minimum availability.
    reason: MinimumReplicasUnavailable
    status: "False"
    type: Available
  - lastTransitionTime: "2022-08-03T08:33:57Z"
    lastUpdateTime: "2022-08-03T08:33:57Z"
    message: ReplicaSet "linglong-server-775d5479f4" is progressing.
    reason: ReplicaSetUpdated
    status: "True"
    type: Progressing
  observedGeneration: 1
  replicas: 1
  unavailableReplicas: 1
  updatedReplicas: 1
