apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "10"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{"deployment.kubernetes.io/revision":"6"},"creationTimestamp":"2022-07-18T12:04:31Z","generation":7,"labels":{"app":"linglong-homepage"},"name":"linglong-homepage","namespace":"default","resourceVersion":"497230","uid":"ae9efb15-a879-4e23-bbe4-13dcae7cbd35"},"spec":{"progressDeadlineSeconds":600,"replicas":1,"revisionHistoryLimit":10,"selector":{"matchLabels":{"app":"linglong-homepage"}},"strategy":{"rollingUpdate":{"maxSurge":"25%","maxUnavailable":"25%"},"type":"RollingUpdate"},"template":{"metadata":{"creationTimestamp":null,"labels":{"app":"linglong-homepage"}},"spec":{"containers":[{"image":"hub.deepin.com/wuhan_v23_linglong/linglong-homepage:develop-snipe","imagePullPolicy":"IfNotPresent","name":"linglong-homepage","resources":{},"terminationMessagePath":"/dev/termination-log","terminationMessagePolicy":"File"}],"dnsPolicy":"ClusterFirst","restartPolicy":"Always","schedulerName":"default-scheduler","securityContext":{},"terminationGracePeriodSeconds":30}}},"status":{"availableReplicas":1,"conditions":[{"lastTransitionTime":"2022-07-18T12:36:13Z","lastUpdateTime":"2022-07-18T12:36:13Z","message":"Deployment has minimum availability.","reason":"MinimumReplicasAvailable","status":"True","type":"Available"},{"lastTransitionTime":"2022-07-18T12:35:59Z","lastUpdateTime":"2022-07-18T13:26:40Z","message":"ReplicaSet \"linglong-homepage-7976bd864c\" has successfully progressed.","reason":"NewReplicaSetAvailable","status":"True","type":"Progressing"}],"observedGeneration":7,"readyReplicas":1,"replicas":1,"updatedReplicas":1}}
  creationTimestamp: "2022-07-18T12:04:31Z"
  generation: 12
  labels:
    app: linglong-homepage
  name: linglong-homepage
  namespace: linglong
  resourceVersion: "955020"
  uid: ae9efb15-a879-4e23-bbe4-13dcae7cbd35
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: linglong-homepage
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/restartedAt: "2022-07-19T10:07:12+08:00"
      creationTimestamp: null
      labels:
        app: linglong-homepage
    spec:
      containers:
      - image: hub.deepin.com/wuhan_v23_linglong/linglong-homepage:develop-snipe
        imagePullPolicy: IfNotPresent
        name: linglong-homepage
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2022-07-18T12:35:59Z"
    lastUpdateTime: "2022-07-19T02:07:14Z"
    message: ReplicaSet "linglong-homepage-6d49f4457f" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  - lastTransitionTime: "2022-08-02T02:23:47Z"
    lastUpdateTime: "2022-08-02T02:23:47Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  observedGeneration: 12
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
