name: Pages

on:
  push:
    branches:
      - main # default branch
      - hexo

jobs:
  pages:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v2
      - name: Set up Git
        uses: actions/setup-python@v2
        with:
          python-version: '3.x' # Replace with your desired Python version
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Merge branch
        run: |
          git config --global user.email "178955347@qq.com"
          git config --global user.name "bot"
          git fetch origin
          git branch
          git pull origin main
          git merge --strategy-option=theirs origin/hexo --allow-unrelated-histories --no-edit
      - name: Bot automatic update
        run: |
          rm -rf source/_posts/*
          find . -name "*.md" -exec sh -c 'sed -i "1 i ---\ndate: $(git log --reverse --pretty=format:"%cd" --date=format:"%Y/%m/%d %H:%M:%S" "{}" | head -1)\nupdated: $(git log --reverse --pretty=format:"%cd" --date=format:"%Y/%m/%d %H:%M:%S" "{}" | tail -1)\n---\n" "{}"' \;
          rsync -avP  --delete --exclude='.git'--exclude='.github' --exclude='node_modules' --exclude='public' --exclude='source' --exclude='scaffolds' --exclude='themes' --include='*/' --include='*.md' --exclude='*' ./ ./source/_posts/
          rsync -avP README.md source/about/index.md
          rm -rf source/_posts/.git source/_posts/.github source/_posts/.gitignore source/_posts/.DS_Store
      - name: Use Node.js 16.x
        uses: actions/setup-node@v2
        with:
          node-version: "16"
      - name: Cache NPM dependencies
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.OS }}-npm-cache
          restore-keys: |
            ${{ runner.OS }}-npm-cache
      - name: Install pandoc
        run: sudo apt install pandoc
      - name: Install Dependencies
        run: npm install
      - name: Build
        run: npm run build
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public