name: Pages

on:
  push:
    branches:
      - main # default branch

jobs:
  pages:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v2
      - name: Set up Git
        uses: actions/setup-python@v2
        with:
          python-version: '3.x' # Replace with your desired Python version
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Rebase branch
        run: |
          git config --global user.email "178955347@qq.com"
          git config --global user.name "wujing"
          git fetch origin main
          git fetch origin auto-pages
          git checkout -b auto-pages origin/auto-pages
          git merge --strategy-option=theirs origin/main --allow-unrelated-histories --no-edit
      - name: new page
        run: |
          find . \( -path ./node_modules -o -path ./source  -o -path ./scaffolds \) -prune -o -type f -name "*.md" ! -name "README.md" | grep md | grep -v linglong | grep -v 玲珑仓库 | xargs -I {} rsync -avzu {} source/_posts
          git add -A .
          git branch -u origin/auto-pages
          git commit -m "feat: new pages"
          git push origin HEAD:auto-pages -f
      - name: Use Node.js 16.x
        uses: actions/setup-node@v2
        with:
          node-version: "16"
      - name: Cache NPM dependencies
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.OS }}-npm-cache
          restore-keys: |
            ${{ runner.OS }}-npm-cache
      - name: install pandoc
        run: sudo apt install pandoc
      - name: Install Dependencies
        run: npm install
      - name: Build
        run: npm run build
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public