name: Pages

on:
  push:
    branches:
      - main # default branch

jobs:
  pages:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 16.x
        uses: actions/setup-node@v2
        with:
          node-version: "16"
      - name: Cache NPM dependencies
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.OS }}-npm-cache
          restore-keys: |
            ${{ runner.OS }}-npm-cache
      - name: install pandoc
        run: sudo apt install pandoc
      - name: Install Dependencies
        run: npm install
      - name: rsync source
        run: rsync -avzu --exclude='.git' --exclude='.github' --exclude='node_modules' --exclude='scaffolds' --exclude='source' --exclude='themes' . source/_posts
      - name: rm !"*.md"
        run: find source/_posts ! -name "*.md" -type f -delete
      - name: rm empty
        run: sudo find source/_posts -mindepth 1 -type f -execdir sh -c 'exit 1' \; -o -type d -empty -delete
      - name: Build
        run: npm run build
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public